import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Course sidebar configuration for Physical AI & Humanoid Robotics textbook.
 * Uses autogenerated sidebar from folder structure with _category_.json files.
 */
const sidebars: SidebarsConfig = {
  courseSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
